### PR TITLE
Replace HashDict by Map

### PR DESCRIPTION
**Pull request by merqlove**
Because of few strange errors:
Elixir 1.3, Erlang 1.9.

This error arrive when i try to unsubscribe not subscribed one.

```
06:05:56.870 [error] GenServer #PID<0.216.0> terminating
** (FunctionClauseError) no function clause matching in HashDict.fetch/2
    (elixir) lib/hash_dict.ex:49: HashDict.fetch(%Redix.PubSub.Connection{backoff_current: nil, continuation: nil, opts: [socket_opts: [], sync_connect: false, backoff_initial: 500, backoff_max: 30000, log: [disconnection: :error, failed_connection: :error, reconnection: :info], exit_on_disconnection: false, host: "127.0.0.1", port: 6379], socket: #Port<0.6346>, subscriptions: #HashDict<[]>}, {:pattern, "MyApp.PubSub.Redis.boo*"})
    (elixir) lib/hash_dict.ex:10: HashDict.get/3
    (redix_pubsub) lib/redix/pubsub/connection.ex:238: anonymous fn/6 in Redix.PubSub.Connection.register_unsubscription/4
    (elixir) lib/enum.ex:957: anonymous fn/3 in Enum.flat_map_reduce/3
    (elixir) lib/enum.ex:2843: Enumerable.List.reduce/3
    (elixir) lib/enum.ex:955: Enum.flat_map_reduce/3
    (redix_pubsub) lib/redix/pubsub/connection.ex:234: Redix.PubSub.Connection.register_unsubscription/4
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:punsubscribe, ["MyApp.PubSub.Redis.boo*"], #PID<0.215.0>}}
State: %Redix.PubSub.Connection{backoff_current: nil, continuation: nil, opts: [socket_opts: [], sync_connect: false, backoff_initial: 500, backoff_max: 30000, log: [disconnection: :error, failed_connection: :error, reconnection: :info], exit_on_disconnection: false, host: "127.0.0.1", port: 6379], socket: #Port<0.6346>, subscriptions: %Redix.PubSub.Connection{backoff_current: nil, continuation: nil, opts: [socket_opts: [], sync_connect: false, backoff_initial: 500, backoff_max: 30000, log: [disconnection: :error, failed_connection: :error, reconnection: :info], exit_on_disconnection: false, host: "127.0.0.1", port: 6379], socket: #Port<0.6346>, subscriptions: #HashDict<[]>}}
```

### CODE REVIEW

**Comment by whatyouhide** [comment]
Hey @merqlove, thanks for contributing. The reason I'm using `HashDict` is that `Redix.PubSub` supports Elixir >= 1.0 and `Map` was really slow for more than a few elements in OTP 17. We can start using maps as soon as the requirement will go up to Elixir >= 1.2. That said, we still need to look into the error you're getting with `HashDict` :)

**Comment by merqlove** [comment]
Hi @whatyouhide , yeah i c. But i really don't understand how i can rescue/catch this error. My tests not fail with it, but it is really strange.
Phoenix.PubSub.Redis doen does not have such problem, because its use sync connection + single global namespace subscribe per each supervised module, to work via Local.

**Comment by whatyouhide** [comment]
Oh I didn't mean you should rescue or handle this error on your side, I meant we should fix this in `Redix.PubSub` :) Do you want to take a stab at it or should I look into it?

**Comment by merqlove** [comment]
I can try to reimplement it in `iex`. Maybe it fails with corrupted object.  Already tried to provide default value for `get`, but it still fails :) 
I'm pretty new in the Elixir/Erlang community, so had seen HashDict only one time before Elixir upgrade in the 2015 :)

**Comment by merqlove** [comment]
Yeah, the problem is in the storage.  Seems HashDict trying to fetch from `Redix.PubSub.Connection` object, instead of HashDict value. When i tried to get not existing from basic HD it not fails, as indeed :)

**Comment by whatyouhide** [comment]
@merqlove yep, that's what the error looks like. It _should_ be relatively easy to fix, I can look at it tonight but feel free to give it a shot if you feel like doing it :)

**Comment by merqlove** [comment]
It corrupts on every second and more unsubscribe.

``` elixir
iex(1)> {:ok, pid} = Redix.PubSub.start_link()
{:ok, #PID<0.192.0>}
iex(2)> Redix.PubSub.unsubscribe(pid, "aaa", self())
:ok
#HashDict<[]>
iex(3)> Redix.PubSub.unsubscribe(pid, "aaa", self())
%Redix.PubSub.Connection{backoff_current: nil, continuation: nil,
 opts: [socket_opts: [], sync_connect: false, backoff_initial: 500,
  backoff_max: 30000,
  log: [disconnection: :error, failed_connection: :error, reconnection: :info],
  exit_on_disconnection: false, host: 'localhost', port: 6379],
 socket: #Port<0.7147>, subscriptions: #HashDict<[]>}
:ok
** (EXIT from #PID<0.190.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in HashDict.fetch/2
        (elixir) lib/hash_dict.ex:49: HashDict.fetch(%Redix.PubSub.Connection{backoff_current: nil, continuation: nil, opts: [socket_opts: [], sync_connect: false, backoff_initial: 500, backoff_max: 30000, log: [disconnection: :error, failed_connection: :error, reconnection: :info], exit_on_disconnection: false, host: 'localhost', port: 6379], socket: #Port<0.7147>, subscriptions: #HashDict<[]>}, {:channel, "aaa"})
        (elixir) lib/hash_dict.ex:10: HashDict.get/3
        (redix_pubsub) lib/redix/pubsub/connection.ex:239: anonymous fn/6 in Redix.PubSub.Connection.register_unsubscription/4
        (elixir) lib/enum.ex:957: anonymous fn/3 in Enum.flat_map_reduce/3
        (elixir) lib/enum.ex:2843: Enumerable.List.reduce/3
        (elixir) lib/enum.ex:955: Enum.flat_map_reduce/3
        (redix_pubsub) lib/redix/pubsub/connection.ex:234: Redix.PubSub.Connection.register_unsubscription/4
        (connection) lib/connection.ex:810: Connection.handle_async/3
```

**Comment by merqlove** [comment]
Problem found.
Inconsistency here:

[lib/redix/pubsub/connection.ex#L252](https://github.com/whatyouhide/redix_pubsub/blob/master/lib/redix/pubsub/connection.ex#L252)

**Comment by merqlove** [comment]
Hot fix is to replace:
`{[], state}` with `{[], acc}`
I can test it again & make PR.

**Comment by whatyouhide** [comment]
@merqlove that would be awesome. We likely need to to the same for [this line](https://github.com/whatyouhide/redix_pubsub/blob/20581e6ec3a645b0ca4d671e6d29c54a80c603b7/lib/redix/pubsub/connection.ex#L255) as well. :)

**Comment by merqlove** [comment]
Looks like fixed. :) I will close this thread for now. Added current replacement to it's own branch for history.

**Pull request closed without merging**
